# Generated by Django 6.1.1 on 2026-09-14 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('summary', models.TextField()),
                ('who_is_affected', models.TextField()),
                ('practical_changes', models.TextField()),
                ('points_of_attention', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generator_reference', models.CharField(max_length=200)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('edited_by_curator', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('origin_body', models.CharField(max_length=200)),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_year', models.IntegerField(blank=True, null=True)),
                ('official_source_url', models.URLField(blank=True, null=True)),
                ('review_notice_override', models.CharField(choices=[('auto', 'Auto'), ('forced_on', 'Forced On'), ('forced_off', 'Forced Off')], default='auto', max_length=20)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bills.accessibleversion')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.theme')),
            ],
        ),
        migrations.AddField(
            model_name='accessibleversion',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('origin_body', models.CharField(max_length=200)),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_year', models.IntegerField(blank=True, null=True)),
                ('official_source_url', models.URLField(blank=True, null=True)),
                ('source_text', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('input_kind', models.CharField(choices=[('pasted', 'Pasted'), ('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('generated', 'Generated'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accessibleversion',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.submission'),
        ),
        migrations.AddField(
            model_name='accessibleversion',
            name='suggested_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.theme'),
        ),
        migrations.AlterUniqueTogether(
            name='accessibleversion',
            unique_together={('bill', 'version_number')},
        ),
    ]
