# Generated by Django 6.1.1 on 2026-09-14 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('generated', 'Generated'), ('regenerated', 'Regenerated'), ('approved', 'Approved'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('rejected', 'Rejected'), ('flag_resolved', 'Flag Resolved'), ('theme_changed', 'Theme Changed'), ('notice_overridden', 'Notice Overridden')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.submission')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.accessibleversion')),
            ],
        ),
    ]
