# Generated by Django 6.1.1 on 2026-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auditentry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accessibleversion',
            index=models.Index(fields=['review_state', 'generated_at'], name='bills_acces_review__d6fb5e_idx'),
        ),
    ]
