# Generated by Django 6.1.1 on 2026-09-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_accessibleversion_bills_acces_review__d6fb5e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
