# Generated by Django 6.1.1 on 2026-10-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='origin_body',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='origin_body',
        ),
    ]
